-- =============================================
-- 设施管理模块 - 数据库表结构
-- =============================================

-- 1. 军标资源表
CREATE TABLE MILITARY_STANDARD (
    MS_ID BIGINT NOT NULL PRIMARY KEY,
    MS_CODE VARCHAR(50) NOT NULL,
    MS_NAME VARCHAR(100) NOT NULL,
    MS_CATEGORY VARCHAR(50),
    MS_VERSION VARCHAR(20),
    DESCRIPTION VARCHAR(500),
    FILE_URL VARCHAR(200),
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE MILITARY_STANDARD IS '军标资源表';
COMMENT ON COLUMN MILITARY_STANDARD.MS_ID IS '军标ID';
COMMENT ON COLUMN MILITARY_STANDARD.MS_CODE IS '军标编码';
COMMENT ON COLUMN MILITARY_STANDARD.MS_NAME IS '军标名称';
COMMENT ON COLUMN MILITARY_STANDARD.MS_CATEGORY IS '军标分类';
COMMENT ON COLUMN MILITARY_STANDARD.MS_VERSION IS '版本号';
COMMENT ON COLUMN MILITARY_STANDARD.DESCRIPTION IS '描述';
COMMENT ON COLUMN MILITARY_STANDARD.FILE_URL IS '文件地址';
COMMENT ON COLUMN MILITARY_STANDARD.STATUS IS '状态（0正常 1停用）';
COMMENT ON COLUMN MILITARY_STANDARD.DEL_FLAG IS '删除标志（0存在 2删除）';

CREATE SEQUENCE SEQ_MILITARY_STANDARD START WITH 1 INCREMENT BY 1;

-- 2. 标签表
CREATE TABLE TAG (
    TAG_ID BIGINT NOT NULL PRIMARY KEY,
    TAG_CODE VARCHAR(50) NOT NULL,
    TAG_NAME VARCHAR(100) NOT NULL,
    TAG_COLOR VARCHAR(20),
    TAG_TYPE VARCHAR(20),
    TAG_ORDER INT DEFAULT 0,
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE TAG IS '标签表';
COMMENT ON COLUMN TAG.TAG_ID IS '标签ID';
COMMENT ON COLUMN TAG.TAG_CODE IS '标签编码';
COMMENT ON COLUMN TAG.TAG_NAME IS '标签名称';
COMMENT ON COLUMN TAG.TAG_COLOR IS '标签颜色';
COMMENT ON COLUMN TAG.TAG_TYPE IS '标签类型';
COMMENT ON COLUMN TAG.TAG_ORDER IS '排序';
COMMENT ON COLUMN TAG.STATUS IS '状态（0正常 1停用）';
COMMENT ON COLUMN TAG.DEL_FLAG IS '删除标志（0存在 2删除）';

CREATE SEQUENCE SEQ_TAG START WITH 1 INCREMENT BY 1;

-- 3. 设施页签表
CREATE TABLE FACILITY_TAB (
    TAB_ID BIGINT NOT NULL PRIMARY KEY,
    TAB_CODE VARCHAR(50) NOT NULL,
    TAB_NAME VARCHAR(100) NOT NULL,
    TAB_ICON VARCHAR(100),
    TAB_ORDER INT DEFAULT 0,
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE FACILITY_TAB IS '设施页签表';
COMMENT ON COLUMN FACILITY_TAB.TAB_ID IS '页签ID';
COMMENT ON COLUMN FACILITY_TAB.TAB_CODE IS '页签编码';
COMMENT ON COLUMN FACILITY_TAB.TAB_NAME IS '页签名称';
COMMENT ON COLUMN FACILITY_TAB.TAB_ICON IS '页签图标';
COMMENT ON COLUMN FACILITY_TAB.TAB_ORDER IS '排序';
COMMENT ON COLUMN FACILITY_TAB.STATUS IS '状态（0正常 1停用）';
COMMENT ON COLUMN FACILITY_TAB.DEL_FLAG IS '删除标志（0存在 2删除）';

CREATE SEQUENCE SEQ_FACILITY_TAB START WITH 1 INCREMENT BY 1;

-- 4. 设施主表
CREATE TABLE FACILITY (
    FACILITY_ID BIGINT NOT NULL PRIMARY KEY,
    FACILITY_CODE VARCHAR(50) NOT NULL,
    FACILITY_NAME VARCHAR(100) NOT NULL,
    PARENT_FACILITY_ID BIGINT,
    TAB_ID BIGINT,
    COUNTRY_CODE VARCHAR(10),
    FACILITY_TYPE VARCHAR(20),
    LOCATION VARCHAR(200),
    LATITUDE DECIMAL(10, 6),
    LONGITUDE DECIMAL(10, 6),
    AREA DECIMAL(10, 2),
    CAPACITY INT,
    DESCRIPTION VARCHAR(500),
    STATUS CHAR(1) DEFAULT '0',
    DEL_FLAG CHAR(1) DEFAULT '0',
    CREATE_BY VARCHAR(64) DEFAULT '',
    CREATE_TIME TIMESTAMP,
    UPDATE_BY VARCHAR(64) DEFAULT '',
    UPDATE_TIME TIMESTAMP,
    REMARK VARCHAR(500)
);

COMMENT ON TABLE FACILITY IS '设施表';
COMMENT ON COLUMN FACILITY.FACILITY_ID IS '设施ID';
COMMENT ON COLUMN FACILITY.FACILITY_CODE IS '设施编码';
COMMENT ON COLUMN FACILITY.FACILITY_NAME IS '设施名称';
COMMENT ON COLUMN FACILITY.PARENT_FACILITY_ID IS '父设施ID（支持层级结构）';
COMMENT ON COLUMN FACILITY.TAB_ID IS '所属页签ID';
COMMENT ON COLUMN FACILITY.COUNTRY_CODE IS '国家代码（如：CN, US, JP）';
COMMENT ON COLUMN FACILITY.FACILITY_TYPE IS '设施类型';
COMMENT ON COLUMN FACILITY.LOCATION IS '位置';
COMMENT ON COLUMN FACILITY.LATITUDE IS '纬度';
COMMENT ON COLUMN FACILITY.LONGITUDE IS '经度';
COMMENT ON COLUMN FACILITY.AREA IS '面积';
COMMENT ON COLUMN FACILITY.CAPACITY IS '容量';
COMMENT ON COLUMN FACILITY.DESCRIPTION IS '描述';
COMMENT ON COLUMN FACILITY.STATUS IS '状态（0正常 1停用）';
COMMENT ON COLUMN FACILITY.DEL_FLAG IS '删除标志（0存在 2删除）';

CREATE SEQUENCE SEQ_FACILITY START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_FACILITY_PARENT ON FACILITY(PARENT_FACILITY_ID);

-- 5. 设施-军标资源关联表
CREATE TABLE FACILITY_MILITARY_STANDARD (
    ID BIGINT NOT NULL PRIMARY KEY,
    FACILITY_ID BIGINT NOT NULL,
    MS_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE FACILITY_MILITARY_STANDARD IS '设施-军标资源关联表';
COMMENT ON COLUMN FACILITY_MILITARY_STANDARD.ID IS '主键ID';
COMMENT ON COLUMN FACILITY_MILITARY_STANDARD.FACILITY_ID IS '设施ID';
COMMENT ON COLUMN FACILITY_MILITARY_STANDARD.MS_ID IS '军标资源ID';
COMMENT ON COLUMN FACILITY_MILITARY_STANDARD.CREATE_TIME IS '创建时间';

CREATE SEQUENCE SEQ_FACILITY_MS START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_FMS_FACILITY ON FACILITY_MILITARY_STANDARD(FACILITY_ID);
CREATE INDEX IDX_FMS_MS ON FACILITY_MILITARY_STANDARD(MS_ID);

-- 6. 设施-标签关联表
CREATE TABLE FACILITY_TAG (
    ID BIGINT NOT NULL PRIMARY KEY,
    FACILITY_ID BIGINT NOT NULL,
    TAG_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE FACILITY_TAG IS '设施-标签关联表';
COMMENT ON COLUMN FACILITY_TAG.ID IS '主键ID';
COMMENT ON COLUMN FACILITY_TAG.FACILITY_ID IS '设施ID';
COMMENT ON COLUMN FACILITY_TAG.TAG_ID IS '标签ID';
COMMENT ON COLUMN FACILITY_TAG.CREATE_TIME IS '创建时间';

CREATE SEQUENCE SEQ_FACILITY_TAG START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_FT_FACILITY ON FACILITY_TAG(FACILITY_ID);
CREATE INDEX IDX_FT_TAG ON FACILITY_TAG(TAG_ID);
