-- =============================================
-- 设施管理模块 - 测试数据
-- =============================================

-- 1. 军标资源测试数据
INSERT INTO MILITARY_STANDARD (MS_ID, MS_CODE, MS_NAME, MS_CATEGORY, MS_VERSION, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_MILITARY_STANDARD.NEXTVAL, 'GJB-001', 'GJB 150A-2009 军用装备实验室环境试验方法', '环境试验', 'V1.0', '规定了军用装备实验室环境试验方法', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO MILITARY_STANDARD (MS_ID, MS_CODE, MS_NAME, MS_CATEGORY, MS_VERSION, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_MILITARY_STANDARD.NEXTVAL, 'GJB-002', 'GJB 181A-2003 飞机结构强度规范', '结构强度', 'V2.0', '规定了飞机结构强度设计要求', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO MILITARY_STANDARD (MS_ID, MS_CODE, MS_NAME, MS_CATEGORY, MS_VERSION, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_MILITARY_STANDARD.NEXTVAL, 'GJB-003', 'GJB 367A-2001 军用通信设备通用规范', '通信设备', 'V1.5', '规定了军用通信设备的通用技术要求', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO MILITARY_STANDARD (MS_ID, MS_CODE, MS_NAME, MS_CATEGORY, MS_VERSION, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_MILITARY_STANDARD.NEXTVAL, 'GJB-004', 'GJB 438B-2009 军用软件开发文档通用要求', '软件开发', 'V3.0', '规定了军用软件开发文档的编制要求', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO MILITARY_STANDARD (MS_ID, MS_CODE, MS_NAME, MS_CATEGORY, MS_VERSION, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_MILITARY_STANDARD.NEXTVAL, 'GJB-005', 'GJB 5000A-2008 军用软件研制能力成熟度模型', '软件质量', 'V2.0', '规定了军用软件研制能力成熟度评价标准', '0', '0', 'admin', CURRENT_TIMESTAMP);

-- 2. 标签测试数据
INSERT INTO TAG (TAG_ID, TAG_CODE, TAG_NAME, TAG_COLOR, TAG_TYPE, TAG_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_TAG.NEXTVAL, 'TAG-001', '重点设施', '#FF0000', '优先级', 1, '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO TAG (TAG_ID, TAG_CODE, TAG_NAME, TAG_COLOR, TAG_TYPE, TAG_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_TAG.NEXTVAL, 'TAG-002', '一般设施', '#00FF00', '优先级', 2, '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO TAG (TAG_ID, TAG_CODE, TAG_NAME, TAG_COLOR, TAG_TYPE, TAG_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_TAG.NEXTVAL, 'TAG-003', '维护中', '#FFA500', '状态', 3, '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO TAG (TAG_ID, TAG_CODE, TAG_NAME, TAG_COLOR, TAG_TYPE, TAG_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_TAG.NEXTVAL, 'TAG-004', '已验收', '#0000FF', '状态', 4, '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO TAG (TAG_ID, TAG_CODE, TAG_NAME, TAG_COLOR, TAG_TYPE, TAG_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_TAG.NEXTVAL, 'TAG-005', '新建', '#800080', '状态', 5, '0', '0', 'admin', CURRENT_TIMESTAMP);

-- 3. 设施页签测试数据
INSERT INTO FACILITY_TAB (TAB_ID, TAB_CODE, TAB_NAME, TAB_ICON, TAB_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY_TAB.NEXTVAL, 'TAB-001', '指挥中心', 'command', 1, '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY_TAB (TAB_ID, TAB_CODE, TAB_NAME, TAB_ICON, TAB_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY_TAB.NEXTVAL, 'TAB-002', '训练场地', 'training', 2, '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY_TAB (TAB_ID, TAB_CODE, TAB_NAME, TAB_ICON, TAB_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY_TAB.NEXTVAL, 'TAB-003', '仓储设施', 'warehouse', 3, '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY_TAB (TAB_ID, TAB_CODE, TAB_NAME, TAB_ICON, TAB_ORDER, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY_TAB.NEXTVAL, 'TAB-004', '通信设施', 'communication', 4, '0', '0', 'admin', CURRENT_TIMESTAMP);

-- 4. 设施测试数据
INSERT INTO FACILITY (FACILITY_ID, FACILITY_CODE, FACILITY_NAME, TAB_ID, FACILITY_TYPE, LOCATION, LATITUDE, LONGITUDE, AREA, CAPACITY, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY.NEXTVAL, 'FAC-001', '第一指挥中心', 1, 'A类', '北京市海淀区', 39.906217, 116.391248, 5000.00, 200, '主要指挥调度中心', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY (FACILITY_ID, FACILITY_CODE, FACILITY_NAME, TAB_ID, FACILITY_TYPE, LOCATION, LATITUDE, LONGITUDE, AREA, CAPACITY, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY.NEXTVAL, 'FAC-002', '第二指挥中心', 1, 'B类', '北京市朝阳区', 39.921489, 116.443108, 3000.00, 100, '备用指挥中心', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY (FACILITY_ID, FACILITY_CODE, FACILITY_NAME, TAB_ID, FACILITY_TYPE, LOCATION, LATITUDE, LONGITUDE, AREA, CAPACITY, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY.NEXTVAL, 'FAC-003', '综合训练场', 2, 'A类', '北京市昌平区', 40.220952, 116.231034, 50000.00, 1000, '大型综合训练场地', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY (FACILITY_ID, FACILITY_CODE, FACILITY_NAME, TAB_ID, FACILITY_TYPE, LOCATION, LATITUDE, LONGITUDE, AREA, CAPACITY, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY.NEXTVAL, 'FAC-004', '室内训练馆', 2, 'B类', '北京市丰台区', 39.858427, 116.286968, 8000.00, 500, '室内综合训练设施', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY (FACILITY_ID, FACILITY_CODE, FACILITY_NAME, TAB_ID, FACILITY_TYPE, LOCATION, LATITUDE, LONGITUDE, AREA, CAPACITY, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY.NEXTVAL, 'FAC-005', '中央仓库', 3, 'A类', '北京市大兴区', 39.728908, 116.338033, 20000.00, 5000, '主要物资储备仓库', '0', '0', 'admin', CURRENT_TIMESTAMP);

INSERT INTO FACILITY (FACILITY_ID, FACILITY_CODE, FACILITY_NAME, TAB_ID, FACILITY_TYPE, LOCATION, LATITUDE, LONGITUDE, AREA, CAPACITY, DESCRIPTION, STATUS, DEL_FLAG, CREATE_BY, CREATE_TIME)
VALUES (SEQ_FACILITY.NEXTVAL, 'FAC-006', '通信基站A', 4, 'A类', '北京市石景山区', 39.906316, 116.222982, 500.00, 50, '主要通信基站', '0', '0', 'admin', CURRENT_TIMESTAMP);

-- 5. 设施-军标资源关联测试数据
-- 第一指挥中心关联军标
INSERT INTO FACILITY_MILITARY_STANDARD (ID, FACILITY_ID, MS_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_MS.NEXTVAL, 1, 1, CURRENT_TIMESTAMP);

INSERT INTO FACILITY_MILITARY_STANDARD (ID, FACILITY_ID, MS_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_MS.NEXTVAL, 1, 3, CURRENT_TIMESTAMP);

-- 综合训练场关联军标
INSERT INTO FACILITY_MILITARY_STANDARD (ID, FACILITY_ID, MS_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_MS.NEXTVAL, 3, 1, CURRENT_TIMESTAMP);

INSERT INTO FACILITY_MILITARY_STANDARD (ID, FACILITY_ID, MS_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_MS.NEXTVAL, 3, 2, CURRENT_TIMESTAMP);

-- 通信基站关联军标
INSERT INTO FACILITY_MILITARY_STANDARD (ID, FACILITY_ID, MS_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_MS.NEXTVAL, 6, 3, CURRENT_TIMESTAMP);

INSERT INTO FACILITY_MILITARY_STANDARD (ID, FACILITY_ID, MS_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_MS.NEXTVAL, 6, 4, CURRENT_TIMESTAMP);

-- 6. 设施-标签关联测试数据
-- 第一指挥中心关联标签
INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 1, 1, CURRENT_TIMESTAMP);

INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 1, 4, CURRENT_TIMESTAMP);

-- 综合训练场关联标签
INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 3, 1, CURRENT_TIMESTAMP);

INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 3, 5, CURRENT_TIMESTAMP);

-- 室内训练馆关联标签
INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 4, 2, CURRENT_TIMESTAMP);

INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 4, 3, CURRENT_TIMESTAMP);

-- 中央仓库关联标签
INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 5, 1, CURRENT_TIMESTAMP);

-- 通信基站关联标签
INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 6, 1, CURRENT_TIMESTAMP);

INSERT INTO FACILITY_TAG (ID, FACILITY_ID, TAG_ID, CREATE_TIME)
VALUES (SEQ_FACILITY_TAG.NEXTVAL, 6, 4, CURRENT_TIMESTAMP);

COMMIT;
